### ISSUE TITLE
kraken_video_player插件提交app store，机器审核被拒问题

### ISSUE THREAD

**Issue by dabing1022** [openkraken/plugins#16]
kraken_video_player插件 iOS的podspec中

```
  s.vendored_libraries = 'libkraken_video_player_jsc.dylib'
```
依赖的是`libkraken_video_player_jsc.dylib`动态库，这个动态库最后被放在了ipa里面的Payload/Frameworks中，在提交审核后，苹果的机器审核给出了拒绝描述：

```
Invalid Swift Support - The files libswiftDarwin.dylib, libswiftDispatch.dylib, libswiftCoreGraphics.dylib, libswiftUIKit.dylib, libswiftCore.dylib, libswiftFoundation.dylib, libswiftQuartzCore.dylib, libswiftObjectiveC.dylib, libswiftCoreImage.dylib aren’t at the expected location /Payload//Frameworks. Move the file to the expected location, rebuild your app using the current public (GM) version of Xcode, and resubmit it
```
这个信息看起来和Swift有关系，但其实没太大关系。

在[官方文档](https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-PROJ_CONFIG-APPS_WITH_DEPENDENCIES_BETWEEN_FRAMEWORKS)上有这么个描述

![image](https://user-images.githubusercontent.com/1892303/128506607-56bf918f-46db-4496-b3ee-09f423bcf918.png)

这里的dylib是否可以打成静态库framework或者.a形式?

**Comment by andycall** [comment]
看样子必须要 framework 才能通过审核。我这边升级一下编译工具链

**Comment by andycall** [comment]
https://github.com/openkraken/native-plugin-build-tool/issues/5

**Comment by dabing1022** [comment]
感谢回复，静候佳音:)

**Comment by andycall** [comment]
试一下 0.4.2

**Comment by dabing1022** [comment]
为你们的快速响应点个赞👍。

好的，下次提审我们使用0.4.2，提交下看看。估计没啥问题。

**Comment by dabing1022** [comment]
![image](https://user-images.githubusercontent.com/1892303/129345001-4fbd1455-6966-4631-8f50-3835a6419c46.png)
使用0.4.2上传app store被机器审核拒绝，原因是bundle id中含有非法的字符


```sh
<string>This bundle is invalid. The bundle at path Payload/zhuanzhuan.app/Frameworks/kraken_video_player.framework has an invalid CFBundleIdentifier 'com.openkraken.plugins.kraken_video_player' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'com.openkraken.plugins.kraken\u005fvideo\u005fplayer' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105]</string>
```

bundle id中只允许数字、字母和连字符-（中划线），因为下划线的问题，导致了bundle id无效。

**Comment by dabing1022** [comment]
![image](https://user-images.githubusercontent.com/1892303/129662379-86b1025e-6533-47ba-bda5-3285bfab2df5.png)
使用0.4.2上传app store被机器审核拒绝，原因是bundle id中含有非法的字符


```sh
<string>This bundle is invalid. The bundle at path Payload/xxx.app/Frameworks/kraken_video_player.framework 
has an invalid CFBundleIdentifier 'com.openkraken.plugins.kraken_video_player' There are invalid characters(characters 
that are not dots, hyphen and alphanumerics) that have been replaced with their code point 
'com.openkraken.plugins.kraken\u005fvideo\u005fplayer' CFBundleIdentifier must be present, must contain only 
alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at 
https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFound
ationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105]</string>
```

bundle id中只允许数字、字母和连字符-（中划线），因为下划线的问题，导致了bundle id无效。

官方文档：[https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105)

![image](https://user-images.githubusercontent.com/1892303/129345564-18325e14-601b-4257-a166-3df24a7bba93.png)

**Comment by andycall** [comment]
好的，我们修改一下

**Comment by dabing1022** [comment]
Invalid Bundle. The bundle xxx.app/Frameworks/kraken_video_player.framework does not support the minimum OS Version specified in the Info.plist.

当时我们自己修改了下bundle id，重新提交了下 又出现了这个问题 还在定位

**Comment by andycall** [comment]
kraken_video_player.framework 最低支持 iOS 9 系统，你的那边是不是版本更低？

**Comment by dabing1022** [comment]
我们app最低从iOS 9开始

![image](https://user-images.githubusercontent.com/1892303/129672896-33b1e8ac-6f83-4aa9-9fff-aae5d065de3e.png)

这就是奇怪的地方 😂

**Comment by andycall** [comment]
bundle id 已经修改了，可以试一下 0.4.3 版本

**Comment by andycall** [comment]
https://github.com/flutter/flutter/issues/58200

可以参考一下

**Comment by dabing1022** [comment]
我们自定义了一个video控件，先绕过去了 😂

**Comment by andycall** [comment]
所以 kraken 的 plugins 还是存在发布问题？

**Comment by dabing1022** [comment]
> [flutter/flutter#58200](https://github.com/flutter/flutter/issues/58200)
> 
> 可以参考一下

之前参考了 各种改版本 还是不行 不知道是哪里不对 其他组件没有这个问题

**Comment by andycall** [comment]
https://github.com/openkraken/plugins/blob/main/packages/kraken_video_player/ios/kraken_video_player.podspec#L18

好像和这个有关
